#include "runs_test_boltach.hpp"
#include "random_excursion_variant_test_boltach.hpp"
#include "runs_test_timoshenko.hpp"
#include "random_excursions_test_timoshenko.hpp"
#include "serial_test_lisai.hpp"
#include "serial_test_zakrevsky.hpp"
#include "spectral_test_lisai.hpp"
#include "non_overlapping_template_matching_test_vecherko.hpp"
